title: 简历 - Web前端开发工程师 - 王昕宇
email: comrade.wang.cn@gmail.com

aboutme:
  name: 王昕宇
  sex: 男
  age: 26
  email: comrade.wang.cn@gmail.com
  phone: 17695457008
  github: https://github.com/comradeWong
  city: 天津
  job: Web前端开发工程师
  edu: 天津工业大学 / 软件工程 / 18届本科

update: 2020年06月02日


# theme: jekyll-theme-cayman
