title: 简历 - 前端开发工程师 - 王昕宇
email: comrade.wang.cn@gmail.com

aboutme:
  name: 王昕宇
  sex: 男
  age: 27
  email: comrade.wang.cn@gmail.com
  phone: 17695457008
  github: https://github.com/comradeWong
  city: 天津
  job: 前端开发工程师
  edu: 天津工业大学 / 软件工程 / 本科
  experience: 5年工作经验

update: 2023年01月27日
# theme: jekyll-theme-cayman
